name: Receive dispatch (publish)

on:
  repository_dispatch:
    types:
      - auto_publish

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upgrade and deploy
        run: |
          yarn upgrade && yarn deploy
